### ISSUE TITLE
Uncaught TypeError: this.addPointerConstraintToMesh is not a function

### ISSUE THREAD

**Issue by sumleo** [beemsoft/webxr-physics#1]
When I use MacOS and Chrome to open (http://www.beemsoft.nl/webvr-physics/) and click on the cube multiple times. It will trigger such kind of error
![image](https://user-images.githubusercontent.com/29517764/59018549-b4a9f100-8878-11e9-9b81-42e41fddb1ce.png)

**Comment by beemsoft** [comment]
The webvr-physics project is not maintained any more.
Please checkout the following code;
https://github.com/beemsoft/webxr-physics/tree/master/experiments
Run it locally using 'npm start'.
