### ISSUE TITLE
TS1259: Module '"events"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

### ISSUE THREAD

**Issue by arpu** [beemsoft/webxr-physics#2]
```
ERROR in /home/arpu/Work/githubsources/webxr-physics/talking-head/src/ray-input/ray-controller.ts
./talking-head/src/ray-input/ray-controller.ts
[tsl] ERROR in /home/arpu/Work/githubsources/webxr-physics/talking-head/src/ray-input/ray-controller.ts(22,8)
      TS1259: Module '"events"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
ℹ ｢wdm｣: Failed to compile.
```

**Comment by beemsoft** [comment]
What node version are you using? And what OS?

**Comment by arpu** [comment]
node --version                                                                                                                                                                                                                      
v12.4.0

fedora 31

**Comment by beemsoft** [comment]
Can you please try to add curled braces:
`import {EventEmitter} from 'events';`

Otherwise, try adding "allowSyntheticDefaultImports": true in compilerOptions in tsconfig.json

**Comment by arpu** [comment]
yeah curled braces works!
